# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Generic


class _Auth(_Generic):
    _type = "auth"
    _icon_dir = "resources/generic/auth"


class AccessToken(_Auth):
    _icon = "access-token.png"


class AccountTakeover(_Auth):
    _icon = "account-takeover.png"


class Actions(_Auth):
    _icon = "actions.png"


class Activity(_Auth):
    _icon = "activity.png"


class AdvancedOptions(_Auth):
    _icon = "advanced-options.png"


class Anticipation(_Auth):
    _icon = "anticipation.png"


class ApiRelated(_Auth):
    _icon = "api-related.png"


class Api(_Auth):
    _icon = "api.png"


class Applications(_Auth):
    _icon = "applications.png"


class Attributes(_Auth):
    _icon = "attributes.png"


class Auth0AuthorizationServer(_Auth):
    _icon = "auth0-authorization-server.png"


class Auth0Dashboard(_Auth):
    _icon = "auth0-dashboard.png"


class Auth0LogoDark(_Auth):
    _icon = "auth0-logo-dark.png"


class Auth0LogoLight(_Auth):
    _icon = "auth0-logo-light.png"


class AuthenticationA(_Auth):
    _icon = "authentication-a.png"


class AuthenticationB(_Auth):
    _icon = "authentication-b.png"


class AuthorizationServer(_Auth):
    _icon = "authorization-server.png"


class Backend(_Auth):
    _icon = "backend.png"


class Biometrics(_Auth):
    _icon = "biometrics.png"


class BotDetection(_Auth):
    _icon = "bot-detection.png"


class BoundaryProtocol(_Auth):
    _icon = "boundary-protocol.png"


class Branding(_Auth):
    _icon = "branding.png"


class BreachedPassword(_Auth):
    _icon = "breached-password.png"


class Browser(_Auth):
    _icon = "browser.png"


class BruteForce(_Auth):
    _icon = "brute-force.png"


class Certificate(_Auth):
    _icon = "certificate.png"


class CliScript(_Auth):
    _icon = "cli-script.png"


class Cloud(_Auth):
    _icon = "cloud.png"


class Consistency(_Auth):
    _icon = "consistency.png"


class Cookies(_Auth):
    _icon = "cookies.png"


class CredentialApplication(_Auth):
    _icon = "credential-application.png"


class CredentialStuffing(_Auth):
    _icon = "credential-stuffing.png"


class CredentialUser(_Auth):
    _icon = "credential-user.png"


class Customization(_Auth):
    _icon = "customization.png"


class Dashboard(_Auth):
    _icon = "dashboard.png"


class Database(_Auth):
    _icon = "database.png"


class DesktopApp(_Auth):
    _icon = "desktop-app.png"


class DeviceBiometrics(_Auth):
    _icon = "device-biometrics.png"


class Efficiency(_Auth):
    _icon = "efficiency.png"


class Empathy(_Auth):
    _icon = "empathy.png"


class EnterpriseDirectory(_Auth):
    _icon = "enterprise-directory.png"


class Extensions(_Auth):
    _icon = "extensions.png"


class FineGrainedAuthorization(_Auth):
    _icon = "fine-grained-authorization.png"


class GettingStarted(_Auth):
    _icon = "getting-started.png"


class GuardianPushNotification(_Auth):
    _icon = "guardian-push-notification.png"


class Help(_Auth):
    _icon = "help.png"


class IdToken(_Auth):
    _icon = "id-token.png"


class IdentifierFirst(_Auth):
    _icon = "identifier-first.png"


class IdentifierPassword(_Auth):
    _icon = "identifier-password.png"


class IntegrationsMarketplace(_Auth):
    _icon = "integrations-marketplace.png"


class IpThrottling(_Auth):
    _icon = "ip-throttling.png"


class LoginCustomization(_Auth):
    _icon = "login-customization.png"


class Login(_Auth):
    _icon = "login.png"


class Logs(_Auth):
    _icon = "logs.png"


class MailMessageA(_Auth):
    _icon = "mail-message-a.png"


class MailMessageB(_Auth):
    _icon = "mail-message-b.png"


class MobileApp(_Auth):
    _icon = "mobile-app.png"


class Monitoring(_Auth):
    _icon = "monitoring.png"


class Multifactor(_Auth):
    _icon = "multifactor.png"


class MultipleFailedLogins(_Auth):
    _icon = "multiple-failed-logins.png"


class OneTimePassword(_Auth):
    _icon = "one-time-password.png"


class Organizations(_Auth):
    _icon = "organizations.png"


class PhoneMessageA(_Auth):
    _icon = "phone-message-a.png"


class PhoneMessageB(_Auth):
    _icon = "phone-message-b-.png"


class PhoneMessageB(_Auth):
    _icon = "phone-message-b.png"


class PipelineA(_Auth):
    _icon = "pipeline-a.png"


class PipelineB(_Auth):
    _icon = "pipeline-b.png"


class PipelineP(_Auth):
    _icon = "pipeline-p.png"


class RefreshToken(_Auth):
    _icon = "refresh-token.png"


class Sdk(_Auth):
    _icon = "sdk.png"


class Security(_Auth):
    _icon = "security.png"


class Server(_Auth):
    _icon = "server.png"


class Settings(_Auth):
    _icon = "settings.png"


class SocialProviders(_Auth):
    _icon = "social-providers.png"


class Spa(_Auth):
    _icon = "spa.png"


class Teams(_Auth):
    _icon = "teams.png"


class Tenant(_Auth):
    _icon = "tenant.png"


class UserDatabase(_Auth):
    _icon = "user-database.png"


class UserManagement(_Auth):
    _icon = "user-management.png"


class User(_Auth):
    _icon = "user.png"


class Users(_Auth):
    _icon = "users.png"


class Video(_Auth):
    _icon = "video.png"


class WebApp(_Auth):
    _icon = "web-app.png"


class Webauthn(_Auth):
    _icon = "webauthn.png"


# Aliases
