# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _IBM


class _Security(_IBM):
    _type = "security"
    _icon_dir = "resources/ibm/security"


class ApiSecurity(_Security):
    _icon = "api-security.png"


class AppId(_Security):
    _icon = "app-id.png"


class BlockchainSecurityService(_Security):
    _icon = "blockchain-security-service.png"


class CertificateManager(_Security):
    _icon = "certificate-manager.png"


class Contrast(_Security):
    _icon = "contrast.png"


class Crypto(_Security):
    _icon = "crypto.png"


class DataSecurity(_Security):
    _icon = "data-security.png"


class DataShield(_Security):
    _icon = "data-shield.png"


class Firewall(_Security):
    _icon = "firewall.png"


class Fusionauth(_Security):
    _icon = "fusionauth.png"


class Gateway(_Security):
    _icon = "gateway.png"


class GovernanceRiskCompliance(_Security):
    _icon = "governance-risk-compliance.png"


class Hsm(_Security):
    _icon = "hsm.png"


class IdentityAccessManagement(_Security):
    _icon = "identity-access-management.png"


class IdentityProvider(_Security):
    _icon = "identity-provider.png"


class InfrastructureSecurity(_Security):
    _icon = "infrastructure-security.png"


class KeyProtect(_Security):
    _icon = "key-protect.png"


class Neuvector(_Security):
    _icon = "neuvector.png"


class OpenBsd(_Security):
    _icon = "open-bsd.png"


class PhysicalSecurity(_Security):
    _icon = "physical-security.png"


class Raxak(_Security):
    _icon = "raxak.png"


class SecretsManager(_Security):
    _icon = "secrets-manager.png"


class SecurityMonitoringIntelligence(_Security):
    _icon = "security-monitoring-intelligence.png"


class SecurityServices(_Security):
    _icon = "security-services.png"


class SslCertificates(_Security):
    _icon = "ssl-certificates.png"


class TrustendComputing(_Security):
    _icon = "trustend-computing.png"


class Twilio(_Security):
    _icon = "twilio.png"


class Vpn(_Security):
    _icon = "vpn.png"


# Aliases
